!! called also for a teacher of a portal or classgroup
<!-- start of $wims_theme/user.phtml -->
!! Class participant page theme.
!nocache
!if $module!=home
 !exit
!endif
!!initialisation
!set home_theme=yes

!set percents=!getscorepercent
!set class_homepage=!getdef class_homepage in wimshome/log/classes/$wims_class/.def
!set etest=!record 0 of wimshome/log/classes/$wims_class/.parmreg/$wims_user.exam
!set n_=!wordcnt $etest

!if / isin $class_homepage and _tool notin $wims_session
  !set deffile=wimshome/log/classes/$wims_class/doc/$class_homepage.def
  !set t_=!getdef titb in $deffile
  !if $t_=$empty or $n_>=4
    !goto normal
  !endif
  !read ./userhome.phtml
  !goto end
!endif

:normal
!read classlogo.phtml
!! On n'affiche pas le logo pour le moment
!set class_logo=$empty
!if $class_logo!=$empty
  <div id="classlogo" class="float_$class_logoside">
    <img src="$class_logo" alt="class logo">
  </div>
!endif
<div id="accueil"></div> <!--pour mettre une css que sur page d'accueil -->
<div id="accueil"></div> <!--pour mettre une css que sur page d'accueil #-->
<!-- Rétablit le titre du thème Nikaia : celui d'Euler est bizarre -->
!!read themes/_widgets/classtitle.phtml
!! décommenter la ligne ci-dessus et commenter les 3 suivantes pour revenir au titre à la Euler
<!-- Lit $wims_theme/script/adm/title.phtml -->
!read themes/$wims_theme/script/adm/title.phtml 2\
$wims_classname - $wims_institutionname
!read adm/class/initclass $wims_superclass, auth

!!FIXME
!!if $auth_method isitemof $auth_method_list
   !!set wims_user_ext=!defof user_external_auth in wimshome/log/classes/$wims_superclass/.users/$wims_user
!!endif
!!default wims_user_ext=$wims_user

!! (MC) the following seems to be needed for groupement to go back to
!! the superclass (is it sufficient to change the name of the variable
!! in the links below?)
!default wims_user_ext=$ext_login

!!<div class="wims_classes_direct">
!!!if $wims_superclass=$empty or $wims_superclass=$wims_class
!!  $wims_institutionname
!!!else
!!  <span class="wims_classes_direct_portal">
!!   !href module=adm/class/classes&type=authparticipant&class=$wims_superclass&auth_user=$wims_user_ext $wims_institutionname
!!  </span>
!!  !if / isin $class_parent and $class_type=1
!!    !set pname=!defof class_description in wimshome/log/classes/$class_parent/.def
!!  / $
!!   <span class="wims_classes_direct_class">
!!  !href module=adm/class/classes&type=authparticipant&class=$class_parent&auth_user=$wims_user_ext $pname
!! </span>
!! !endif
!!!endif
!!</div> <!--wims_classes_direct-->

!! GM 16/01/2023 Message Alerte aussi dans espace eleve !!
!let manag_msg=!fileexists wimshome/log/manager_msg.phtml.$lang
!if $manag_msg=yes
  !!<div id="wims_class_manager_msg" class="wims_class_manager_msg">
  <div id="wims_class_manager_msg" class="wims_msg warning">
    !read ./wimshome/log/manager_msg.phtml.$lang
  </div>
  <br class="spacer">
!endif


<div class="wims_content">

!if _tool isin $wims_session
  !read ./tools.phtml
  !goto end
!endif

!if $n_>=4
  !read themes/_widgets/examsession.phtml $etest
  !if $shortout!=$empty
    !goto end
  !endif
!endif
<p class="wims_greetings">$U_greet</p>


!!on affiche le bouton "mes notes" si on est dans un cours ou dans une classe individuelle ou dans une classe d'un groupement
!if ($class_type=1 and ($class_typename=course or $class_typename=class) or ($class_type=0))
	<div class="wimscenter">
	  !set wims_ref_class=wims_button
	  !href module=adm/class/userscore Mes notes
	</div>
!endif

!if & isin $newmsgcnt or $newmsgcnt>0
  <p class="wims_msg info">
    !href module=adm/forum/mboard $U_newmsg
  </p>
!endif

!if $wims_supconnectshowed=yes and $wims_supervisorconnected!=$empty
  <p class="wims_connected">$U_supconnected</p>
!endif

!readproc wimshome/log/classes/$wims_class/.users/$wims_user

!!! Blocs actu-exemples
!if $class_type isin 24 and $user_supervisable=yes
  !read themes/$wims_theme/widgets/newsexample.phtml
!endif

!set motispresent_=!record 0 of wimshome/log/classes/$wims_class/.motd
!if $motispresent_!=$empty and $mot_ notsametext <br>
  !if $class_type isin 01
  <div class="accordion " data-accordion  data-allow-all-closed="true" style="background:transparent;">
    <div id="motdj_accordion" class="accordion-item " data-accordion-item>
      <a  href="#" class="wims_button BtnHideShow2" style="border-radius:0.4em" title="$euler_btn_hide_show_title2" onclick="addClicks2();">$euler_btn_show2</a>
      <div  class="accordion-content" data-tab-content style="background:transparent; padding:0;border:0;">
  !endif
        !read themes/_widgets/motd.phtml
  !if $class_type isin 01
      </div>
    </div>
  </div>
  !endif
!endif

!if $class_type>=2
  !read ./subclasses.phtml
  !set is_interclass=yes
!endif

!set seq_cnt=!record 0 of wimshome/log/classes/$wims_class/seq/.sequences
!set seq_cnt=!line 1 of $seq_cnt
!set seq_open=!defof sequence_open in wimshome/log/classes/$wims_class/seq/.def

!if $seq_open=yes
  !if $seq_cnt>0
    !read themes/_widgets/sequence.phtml
    !if $jquery_defined=yes
      <script>
        jQuery(function($$){
              $$('fieldset.wims_work_legend').append('<style>legend::before{content: "\\25BA  ";padding-left:0.5em;}</style>');
            });
        jQuery(function($$){
          $$('fieldset.wims_work_legend').attr({"id":"seq_legend","style":"cursor:pointer;text-align:left;","onclick":"jQuery('#seq_legend #euler_legend').slideToggle(500);"});
        });
        jQuery(function($$){
           $$('fieldset.wims_work_legend legend').attr({"align":"left","title":"$euler_hide_show_legend"});
        });
        jQuery(function($$){
          $$('fieldset.wims_work_legend ul').attr({"id":"euler_legend","style":"display:none;"});
        });
      </script>
    !endif
  !endif
  !goto endbar
!endif

!!define variable $dcnt and dpcnt
!read themes/_widgets/user_vardoc.phtml
!read themes/_widgets/user_vardocp.phtml

!!define variable $n
!read themes/_widgets/user_varsheet.phtml

!!define variable $m
!read themes/_widgets/user_varexam.phtml

!!define variable $v
!read themes/_widgets/user_varvote.phtml

!!define variable $gr
!read themes/_widgets/user_varmanual.phtml

!!define variable $tcnt
!read themes/_widgets/user_vartool.phtml

!!define variable $fwcnt
!read themes/_widgets/user_varfreework.phtml

!!define variable $gcnt
!read themes/_widgets/user_varglossary.phtml
<div id="widget_user_list">

  !ifval $gcnt+$tcnt+$dcnt+$dpcnt+$n+$m+$v+$fwcnt>1
    !if $jquery_defined=yes
      !read adm/tabscript user_list
    !endif
    <ul id="wims_user_summary">
      !if $[$dcnt+$dpcnt]>0
        <li><a class="wims_doc_item" href="#wims_user_doc">$wims_name_Docs</a></li>
      !endif
      !if $n>0
        <li><a class="wims_sheet_item" href="#wims_user_sheet">$wims_name_Sheets</a></li>
      !endif
      !if $m>0
        <li><a class="wims_exam_item" href="#wims_user_exam">$wims_name_Examens</a></li>
      !endif
      !if $v>0
        <li><a class="wims_vote_item" href="#wims_user_vote">$wims_name_Votes</a></li>
      !endif
      !if $tcnt+$gcnt>0
        <li><a class="wims_tool_item" href="#wims_user_tool">$wims_name_tools</a></li>
      !endif
      !if $fwcnt>0
        <li><a class="wims_freework_item" href="#wims_user_freework">$wims_name_Freeworks</a></li>
      !endif
    </ul>
  !endif

  !read themes/_widgets/userdoc.phtml
  !read themes/_widgets/usersheet.phtml
  !read themes/_widgets/userexam.phtml
  !read themes/_widgets/uservote.phtml
  !read themes/_widgets/usertool.phtml
  !read themes/_widgets/userfreework.phtml
</div>

!!retiré le 7/07/22 GM
!!if $class_type notin 24
  !!!read adm/class/seq_legend.phtml
!!endif
!!!

!!if $jquery_defined=yes
  !!<script>
    !!jQuery(function($$){
      !!$$('fieldset.wims_work_legend').attr({"id":"seq_legend","style":"cursor:pointer;text-align:left;","onclick":"jQuery('#seq_legend #euler_legend').slideToggle(500);"});
    !!});
    !!jQuery(function($$){
       !!$$('fieldset.wims_work_legend legend').attr({"align":"left","title":"$euler_hide_show_legend"});
    !!});
    !!jQuery(function($$){
      !!$$('fieldset.wims_work_legend ul').attr({"id":"euler_legend","style":"display:none;"});
    !!});
  !!</script>
!!endif

<br class="clearall">

!ifval $gcnt+$tcnt+$dcnt+$dpcnt+$n+$m+$v+$fwcnt=0
  !if $is_interclass!=yes
    <div class="wims_msg info">$U_nosheet</div>
  !endif
!endif

:endbar
!!read themes/$wims_theme/widgets/seq_legend.phtml
</div><!--wims_content-->
</div><!--wimsbody-->
</div><!--wimspagebox-->


!read themes/_procs/usermenumodubox.proc

!set wims_homeref_n0=!linecnt $wims_rm_0

!!must have read user*.phtml,  with *=sheet, exam must be read before
!distribute items ul,li into div0,div1
!!read themes/_widgets/menumodubox.phtml
!read themes/$wims_theme/_widgets/usermenubox.phtml
!reset div0 div1

!read themes/_widgets/topback.phtml

</div><!--end of wimsbodybox-->

:end
!read themes/_widgets/session_warn.phtml
!read themes/$wims_theme/_widgets/footer_foundation.phtml

</body>
</html>
<!-- end of $wims_theme/user.phtml -->