<!-- start of $wims_theme/visitor.phtml -->
!! WIMS main entrance page theme.
!nocache
!if $module!=home
 !exit
!endif
!! yet useful ??
!!set wims_name_browse=$N_browse2
!set home_theme=yes
!set table_colors=$wims_ref_bgcolor,$wims_ref_bgcolor

</div>


<div class="off-canvas position-left" id="offCanvas3" data-off-canvas>
     Your menu or Off-canvas content goes here -->
      <button class="close-button" aria-label="Close menu" type="button" data-close>
  <span aria-hidden="true">&times;</span>
</button>

<div>coucou</div>hello
  </div>
  

<div class="title-bar">
    <button class="menu-icon" type="button" data-open="offCanvas3"></button>
    <span class="title-bar-title">Foundation title bar with top off-canvas</span>
</div>

<div class="off-canvas-content" data-off-canvas-content>
     Your page content lives here -->
     
     cette page est pour essayer de regrouper le menu hamburger et la div de gauche...
     <br>
     c'est foundation derniere version, donc on peut peut-être alors enlever les fichiers css de la vieille foundation
     <br>
      
</div>

<div id="wimsfrontpage" >
	<div id="wimsbodybox" >
		<div id="wimspagebox" class="grid-container fluid" >
			<div class="wimsbody">
				<!-- Administration du serveur local-->
					!read themes/_widgets/manager.phtml
				<!--Contenu de la page d'accueil-->

				!let motd_msg=!fileexists wimshome/log/motd.phtml.$lang
				!if $motd_msg=yes
				  <div id="wims_class_manager_msg" class="wims_widget_box small-12 cell ">
					  <div class="euler_box_content" style="min-height: 0;">
							!read ./wimshome/log/motd.phtml.$lang
					 </div>
				  </div>
				  <br class="spacer">
				!endif
				
				!read themes/$wims_theme/widgets/newsexample.phtml

				<div class="grid-x grid-margin-x 3blocs" >
					  <!--Recherche classes-->
					  !read themes/$wims_theme/widgets/search_classe.phtml
					<!-- Recherche par mot clé -->
					!read themes/$wims_theme/widgets/search_engine.phtml
					<!-- Recherche par toxonomie ou lexique -->
					!read themes/$wims_theme/widgets/lexique.phtml
				</div>

				<div class="grid-x grid-margin-x">

					!if $s_category=V
						 <!--Exemples de contenus-->
						 !! Modifié par jlben pour le thème Euler le 22/6/19 et GM le 11/07/19 avec nouvelles variables
						 !read themes/$wims_theme/widgets/front.phtml
					!else
					 <!--Résultats recherche exercices-->
					 !!! GM 14/10/20 retour au fichier original avec css ici
					 <div class="wims_widget_box small-12 cell ">
   						<div class="euler_box_content">
      						<div class="euler_title_box">
       						 <h3 class="euler_wims_title">$euler_result</h3>
      						</div>
					 	!read ./result.phtml
					 	</div>
					 </div>
					!endif
				</div>

			</div><!--end wimsbody-->
		</div><!--wimspagebox-->

		!set wims_show_stat=!tolower $wims_show_stat

	</div><!--wimsbodybox-->

    !! User opts
    !! Voir dans scripts/adm/oneitem.phtml la signification de la ligne suivante
    !if $lang=fr
  		!set contactus=!mailurl $wims_site_manager Nous contacter\
  		EULER-WIMS
  	!else
  		!set contactus=!mailurl $wims_site_manager Webmaster\
  		EULER-WIMS
  	!endif
  	!set wims_tail_home = !append line text_icon mail,01,$contactus to $wims_tail_home
    !set wims_tail_home = !append line pref,1,module=adm/light&phtml=useropts.phtml.$lang to $wims_tail_home
    !set wims_tail_home = !append line mod_new,1,module=adm/new to $wims_tail_home
    !set wims_tail_home = !append line stat,1,module=adm/stat/stat to $wims_tail_home
    !set wims_tail_home = !append line ref,1,module=adm/stat/referer to $wims_tail_home
    !!set wims_tail_home = !append line download,1,module=adm/light&phtml=download.phtml.$lang to $wims_tail_home
    !increase $wims_tail_home_n0

    !distribute items ul,li into div0,div1
	!read themes/_widgets/visitormenubox.phtml
    !reset div0 div1

    !!*** Pour thème Euler GM 9/07/19 Normalement ce fichier affiche le logo de l'institution après le footer. Détourné pour y mettre le lien vers Nous Contacter***!!
	!! GM 01/01/22 Nous contacter retiré et déplacé dans le footer noir
	!!read themes/$wims_theme/_widgets/tailbox.phtml

 </div><!--wimsfrontpage-->

!!!read themes/_widgets/topback.phtml

!read themes/$wims_theme/_widgets/footer_foundation.phtml

 </body>
</html>
<!-- end $wims_theme/visitor.phtml -->
