<!-- start Pion/widgets/sandwich.phtml-->


!!sur la page d'accueil le menu est différent. Sur les autres pages, le menu est dans Pion/tail.phtml...
!if $module=home and $wims_user!=supervisor or $module=home and $class_typename notin portal,level
<div id = "menu-principal" class ="off-canvas position-left" data-off-canvas>
	<div class="menu" style="width: 225px;">
	!if $[$wims_home_items_cnt + $wims_hm_cnt + $wims_link_close_cnt]!=0 or ($module_path notitemof home,adm,classes and _exam notin $session and $module_init_parm == $empty)
		!! le widget permalien ajoute un bouton "partager ce module" dans certaines conditions
		!read themes/$wims_theme/widgets/permalink.phtml
		!reset div0 div1
	!endif
	<ul class="menu vertical" data-responsive-menu="drilldown medium accordion">
		!! s'affiche sur la page d'accueil des visiteurs
		!if $module isitemof home,adm/class/classes,adm/modtool and ($wims_user=$empty)
			!if $type!=participant
				<li class="menuitem n_participant">
				!read ./adm/oneitem.phtml n_participant,1,module=adm/class/classes&type=participant
				</li>
			!endif
			!if $type!=supervisor
				<li class="menuitem n_supervisor">
					!read ./adm/oneitem.phtml n_supervisor,1,module=adm/class/classes&type=supervisor
				</li>
			!endif
		!endif
		!if $module=home and $wims_user=$empty
			!! Help link
			!set wims_hm = !append line help,4,module=help/main,help to $wims_hm
			!increase $wims_hm_cnt
		!endif

		!read themes/$wims_theme/_widgets/user_links.phtml
		
		!! Menu specifique au module actuel
		!!if $module != adm/class/classes
		!!	  !! affiche le menu si le module n'est pas la zone enseignant
		!!	  !distribute items ul,li into div0,div1
		!!	  !read themes/$wims_theme/_widgets/menumodubox.phtml
		!!endif
	</ul>
	</div>
	!!bouton de fermeture du menu sandwich
	<button class="close-button" aria-label="Close menu" type="button" data-close>
		<span aria-hidden="true">&times;</span>
	</button>
	
</div>
!endif

<!-- end Pion/widgets/sandwich.phtml-->
