<!-- start Pion/widgets/sandwich2.phtml-->


!! Menu specifique au module actuel
	!!div qui contient le menu activable par le "sandwich"
	!if $wims_homeref_n0+$wims_homeref_n4 + $wims_homeref_n5 >0  
		<div id = "menu-principal" class ="off-canvas position-left" data-off-canvas>		
			<div class="menu2bis">
			!distribute items ul,li into div0,div1
			!read themes/$wims_theme/_widgets/menumodubox.phtml
			!!bouton de fermeture du menu sandwich
			</div>
			<button class="close-button" aria-label="Close menu" type="button" data-close>
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
	!endif
	
<!-- end Pion/widgets/sandwich2.phtml-->
