<!-- start Pion/widgets/sandwich2.phtml-->


!! Menu specifique au module actuel
	!!div qui contient le menu activable par le "sandwich"
	<div id = "menu-principal" class ="off-canvas position-left" data-off-canvas>		
		<div>
		!distribute items ul,li into div0,div1
		<ul> ok
			!read themes/$wims_theme/_widgets/menumodubox.phtml
		</ul>
		!!bouton de fermeture du menu sandwich
		<button class="close-button" aria-label="Close menu" type="button" data-close>
			<span aria-hidden="true">&times;</span>
		</button>
		</div>
	</div>
	
<!-- end Pion/widgets/sandwich2.phtml-->
