<!-- start $wims_theme/widgets/topbox.phtml -->
<!-- Je place la title-bar en dehors de wimstopbox pour pouvoir la rendre sticky -->
<div id="wimstopbox">
	!read themes/$wims_theme/_widgets/site_title.phtml
	!distribute items li into div1 
	
</div><!-- end de wimstopbox-->
<div class="title-bar" data-hide-for="medium">
	!!bouton "menu sandwich"
	<button class="menu-icon" type="button" data-open="menu-principal"></button>
	<!-- wims_user = $wims_user -->
	<!-- style = $style -->
	!if $wims_user=supervisor and $style!=student
	<!-- On affiche le fil d'Ariane seulement pour les enseignants -->
		<span class="title-bar-title"> 
			!if $wims_lightpopup!=yes
				!!read themes/Pion/_widgets/ariane.phtml
				!set wims_ariane_self=no
				!read themes/_widgets/ariane.phtml
			!endif
		</span>
	!endif
	!read themes/Pion/_widgets/choix_enseignant_eleve.phtml
	<!-- Section à gauche -->
	<div class="title-bar-left">
		!if $wims_participate!=$empty
		<!-- On affiche le bouton Accueil seulement pour les élèves -->
			!! je lis ariane.proc pour avoir le lien de la page d'accueil
			!read themes/_procs/ariane.proc
			!! c'est le 3e élément de la première liste de wims_ariane_list
			!set lien_home=!line 1 of $wims_ariane_list
			!set lien_home=!item 3 of $lien_home
			!set home_url=wims.cgi?session=$wims_session&lang=$lang&$lien_home
			<a href="$home_url" class="retour_accueil">
				Accueil
			</a>
		!endif
	</div>

	<!-- Section centrée (pour le chronomètre) -->
	<div class="title-bar-center">
		<!-- Le chronomètre sera inséré ici par JavaScript -->
	</div>

	<!-- Section à droite -->
	<div class="title-bar-right">
	!set retour_ex=retour_exo
	!read themes/$wims_theme/_widgets/retour_exos.phtml
	<script>
	  	var el = document.querySelector('.retour_exo');
		if (el && !window.opener) {
 				el.style.display = 'none';
		}
	</script>
	!read themes/$wims_theme/_widgets/logout_title.phtml
	</div>
</div>
!read themes/$wims_theme/widgets/sandwich.phtml
<!-- end title-bar -->

<!-- end $wims_theme topbox Widget -->
