<!-- start $wims_theme/widgets/topbox.phtml -->


<div id="wimstopbox">
	!read themes/$wims_theme/_widgets/site_title.phtml
	!distribute items li into div1 
	
	<div class="title-bar" data-hide-for="medium">
		!!bouton "menu sandwich"
		<button class="menu-icon" type="button" data-open="menu-principal"></button>
		<span class="title-bar-title"> 
			!if $wims_lightpopup!=yes
			!read themes/Pion/_widgets/ariane.phtml
			!endif
		</span>
			!read themes/$wims_theme/_widgets/logout_title.phtml

	</div>
	!read themes/$wims_theme/widgets/sandwich.phtml
	<!-- end title-bar -->
</div><!-- end de wimstopbox-->
<!-- end $wims_theme topbox Widget -->
