!! options :
!! wims_ariane_home = no ==> don't use $wims_home_items
!! wims_ariane_self = no ==> don't generate automatically : home / module
!if $wims_ariane_home=no and $wims_ariane_self=no and $wims_ariane=$empty
  !exit
!endif

!read themes/_procs/ariane.proc
<!-- $wims_theme/_widgets/ariane.phtml -->
<nav aria-label="You are here:">
  <ul class="breadcrumbs">
  !for i_=1 to $wims_ariane_cnt
    !set 1_=!line $i_ of $wims_ariane_list
    !if " notin $(1_[1]) and * notin $(1_[1])
      !set wims_ref_class = !word 1 of $(1_[1])
    !endif
    !! Ajout Pion : si on est à l'accueil d'une classe, on affiche juste l'icône "Accueil" (n°6 dans oneitem.phtml) et sinon, on affiche le texte sans icône 
    !set mot=!word 1 of $(1_[1])
    !set mot2=!word 2 of $(1_[1])
    !if $mot=class_home and $mot2=$empty or $mot=home and $mot2=$empty
      !set 1_=$(1_[1]) Accueil,6
    !else
      !set 1_=!replace internal class_home by no-icon in $1_
    !endif
    !if $wims_ref_class!=$empty
      !set css_class = class="$wims_ref_class menuitem"
    !endif
<li $css_class>
      !if $i_!=$wims_ariane_cnt
		!read $(w_path)oneitem.phtml $1_
      !else
		!set 1_=!replace internal no-icon by in $1_
		!set mot2=!replace internal class_home by in $(1_[1])
		!set mot2=!replace internal home by in $mot2
        <span class="text_item no-icon">$mot2</span><span class="show-for-sr">(Current)</span>
      !endif
    </li>
    !reset css_class
  !next
  </ul>
</nav>
<!-- end of $wims_theme/_widgets/ariane.phtml -->
!!reset wims_ariane_home wims_ariane_self
