!! options :
!! wims_ariane_home = no ==> don't use $wims_home_items
!! wims_ariane_self = no ==> don't generate automatically : home / module
!if $wims_ariane_home=no and $wims_ariane_self=no and $wims_ariane=$empty
  !exit
!endif

!read themes/_procs/ariane.proc
<!-- $wims_theme/_widgets/ariane.phtml -->
<nav aria-label="You are here:">
  <ul class="breadcrumbs">
<!-- wims_ariane_cnt = $wims_ariane_cnt -->
<!-- wims_ariane_list = $wims_ariane_list -->
<!-- Boucle : -->
<!-- wims_ref_class = $wims_ref_class -->
  !for i_=1 to $wims_ariane_cnt
  <!-- i_ = $i_ -->
    !set 1_=!line $i_ of $wims_ariane_list
    <!-- 1_ = $1_ -->
    <!-- Ajout SC : si c'est le premier élément, on change la classe pour garder l'icône -->
    !set premier_arg = !item 1 of $1_
    <!-- premier_arg = $premier_arg -->
    !if " notin $(1_[1]) and * notin $premier_arg
      !set wims_ref_class = !word 1 of $premier_arg
    !endif
    <!-- wims_ref_class = $wims_ref_class -->
    <!-- 1_[1] = $(1_[1]) -->
    !if $i_==1    
      <!-- si premier élément du fil d'arianne, on affiche juste l'icône -->
      <!-- -> argument 2 de oneitem doit être égal à 6-->
      !set debut=!item 1 of $1_
      !set fin=!item 3 to -1 of $1_
      !set 1_=$debut,6,$fin
      !set 1_=!replace class_home by class_home_first in $1_
      <!-- 1_ = $1_ -->
    !endif
    !if $wims_ref_class!=$empty
      !set css_class = class="$wims_ref_class menuitem"
    <!-- On définit le(s) mot(s) à afficher dans cet élément de liste du fil d'ariane -->
      !set premier_arg = !replace " by in $premier_arg
      <!-- premier_arg = $premier_arg -->
      !set w_name1=!word 1 of $premier_arg
      !set w_name2=!word 2 to -1 of $premier_arg
      !set w_name=$(wims_name_$(w_name1)) $w_name2
      <!-- w_name = $w_name -->
      !set w_name=!replace $wims_name_class_home by in $w_name
      !set champ1 = !item 1 of $1_
      !set champ2 = !item 2 of $1_
      !set champ3 = !item 3 of $1_
      !set champ4 = !item 4 of $1_
      !set 1_ = $champ1,$champ2,$champ3,$champ4,$w_name
    !else
      !set w_name=$premier_arg
    !endif
    <!-- w_path = $w_path -->
    <li $css_class>
      !read themes/$wims_theme/script/oneitem_modif.phtml $1_
      <!-- wims_ref_title = $wims_ref_title -->
      !if $i_=$wims_ariane_cnt
        <span class="show-for-sr">(Current)</span>
      !endif
    </li>
    !reset w_name
    !reset css_class
  !next
  </ul>
</nav>
<!-- end of $wims_theme/_widgets/ariane.phtml -->
!!reset wims_ariane_home wims_ariane_self
