!if $module = home
  !! use scripts/adm/oneitem.phtml
  !set w_path = ./adm/
!else
  !! use html/oneitem.phtml
  !set w_path = $empty
!endif
!read themes/$wims_theme/local.phtml
!set wims_rm_0=!append line $wims_rm_0 to $wims_local_menu_items

!read themes/_procs/homemenu.proc
!if $wims_homeref_n0=1 and itemsep isin $wims_rm_0
  !set wims_homeref_n0=0
!endif
!!delete a line itemsep,0 at the beginning without third argument
!set wims_rm_0=!nonempty line $wims_rm_0
!set tmp_=!line 1 of $wims_rm_0
!if itemsep isitemof $(tmp_[1]) and $(tmp_[3])=$empty
  !set wims_rm_0=!line 2 to -1 of $wims_rm_0
!endif
!set tmp_=!line -1 of $wims_rm_0
!if (itemsep isitemof $(tmp_[1]) or $(tmp_[1])=$empty) and $(tmp_[3])=$empty
  !set wims_rm_0=!line 1 to -2 of $wims_rm_0
!endif

!set wims_homeref_n0=!linecnt $wims_rm_0
!if $wims_homeref_n0+$wims_homeref_n4 + $wims_homeref_n5 >0  
  
  <!-- Pion/_widgets/menumodubox.phtml -->  
  !if $wims_homeref_n0>0
    !for i_=1 to $wims_homeref_n0
      !set 1_=!line $i_ of $wims_rm_0
      !if $(1_[1])$(1_[2]) != $empty
        !set is_link=!item 2 of $1_
        !if $is_link!=0
          !set wims_ref_class = !item 1 of $1_
          !set wims_ref_class = !word 1 of $wims_ref_class
          !if " isin $wims_ref_class
            !reset wims_ref_class
          !endif
          !!-- SC : ce if pour supprimer le texte "class_home" en tête du menu sandwich 
          !!--PB : pas réussi à faire mieux. Les mots en français sont dans public_html/html/name.phtml.fr mais il n'y a pas de "class_home" et quand j'en ai ajouté un ça n'a rien fait (et c'est hors du dossier du theme...)
          !if $wims_ref_class != class_home 
            <$div1 class="menuitem $wims_ref_class">
              !read $(w_path)oneitem.phtml $1_
            </$div1>
          !endif
            !reset wims_ref_class
        !else
          !set item_text = !item 3 of $1_
          !if $item_text notsametext $empty
            <h5 class="menu_title"><span>
              !read $(w_path)oneitem.phtml $1_
            </span></h5>
          !endif
          
        !endif
      !endif
   !next i_
   
   !! Thème Pion : menus simplifiés (voués à disparaître)
   !if $menusimpl=1 and ($wims_typename isitemof program,class,course) and ($wims_user=supervisor)
   	   !set wims_ref_class=plus-square
	   <li class="menuitem plus-square">
	   !href cmd=resume&menusimpl=2 <span>$menu_simpl</span>
	   </li>
   !endif
	  
  !endif wims_homeref_n0

  !if $wims_homeref_n5>0
    <$div0 class="wimsmenu menu homeref_n5">
    !for i_=1 to $wims_homeref_n5
      !if $div0=ul
        <li class="menuitem">
      !endif
      !set 1_=!line $i_ of $wims_rm_5
      !read $(w_path)oneitem.phtml $1_
      !if $div0=ul
        </li>
      !endif
    !next i_
  !endif wims_homeref_n5

  !if $wims_homeref_n4>0
    <$div0 class="wimsmenu menu homeref_n4">
    !for i_=1 to $wims_homeref_n4
      !set 1_=!line $i_ of $wims_rm_4
      !set wims_ref_class = !item 1 of $1_
      !if " isin $wims_ref_class
        !reset wims_ref_class
      !endif
      <$div1 class="menuitem $wims_ref_class">
        !read $(w_path)oneitem.phtml $1_
      </$div1>
      !reset wims_ref_class
    !next i_
  !endif wims_homeref_n4
  <!-- end Pion/_widgets/menumodubox.phtml -->
!endif wims_homeref_n0+wims_homeref_n4+$wims_homeref_n5
