
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!ajouté mais à vérifier    
      !set wims_user_links=!append line mail,1,module=adm/class/sendmail&job=oneuser&target=supervisor\
to $wims_user_links
      !set wims_user_links=!append line forum $name_c,1,module=adm/forum/mboard\
to $wims_user_links
      !set wims_user_links=!append line passwd,1,module=adm/class/passwd&job=user\
to $wims_user_links
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
